repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: django-check
        name: Django System Check
        entry: python manage.py check
        language: system
        pass_filenames: false
