# Generated by Django 4.2.30 on 2026-04-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='gstin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GSTIN / Tax Details'),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='These will appear at the bottom of your invoices', null=True),
        ),
    ]
