# Generated by Django 4.2.30 on 2026-07-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shop_gstin_shop_logo_shop_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='next_sku_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shop',
            name='scanner_suffix',
            field=models.CharField(choices=[('ENTER', 'Enter'), ('TAB', 'Tab'), ('NONE', 'No Suffix')], default='ENTER', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='sku_prefix',
            field=models.CharField(blank=True, help_text='Custom SKU prefix (e.g. SHIV). If empty, defaults to shop name initials.', max_length=10, null=True),
        ),
    ]
