# Generated by Django 4.2.30 on 2026-07-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backfill_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='subscription_plan',
        ),
    ]
