# Generated by Django 4.2.30 on 2026-07-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_shop_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subscriptionplan'),
        ),
    ]
