# Generated by Django 4.2.30 on 2026-08-18 18:46

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_shop_logo_path, validators=[core.validators.validate_image_upload]),
        ),
    ]
