# Generated by Django 4.2.30 on 2026-07-01 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_shop_next_sku_number_shop_scanner_suffix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_jewelleryitem_barcode_svg_jewelleryitem_barcode_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('width_mm', models.IntegerField(default=50)),
                ('height_mm', models.IntegerField(default=25)),
                ('custom_css', models.TextField(blank=True, help_text='CSS overrides for printing layout alignment', null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(blank=True, help_text='Null means global preset template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_templates', to='core.shop')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='BarcodeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SCAN_SUCCESS', 'Scan Success'), ('SCAN_FAILED', 'Scan Failed'), ('PRINT_LABEL', 'Print Label'), ('PRINT_BULK', 'Print Bulk Labels'), ('QR_SCAN', 'QR Mobile Scan'), ('BARCODE_GENERATED', 'Barcode Generated')], max_length=30)),
                ('sku_snapshot', models.CharField(blank=True, help_text='SKU identifier at the moment of log execution', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_events', to='inventory.jewelleryitem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_events', to='core.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='labeltemplate',
            constraint=models.UniqueConstraint(fields=('shop', 'slug', 'version'), name='unique_template_version_per_shop'),
        ),
    ]
