# Generated by Django 4.2.30 on 2026-06-05 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_shop_gstin_shop_logo_shop_terms_and_conditions'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelleryitem',
            name='metal_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='metal_rate_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='metal_type',
            field=models.CharField(choices=[('GOLD_24K', 'Gold 24K'), ('GOLD_22K', 'Gold 22K'), ('GOLD_18K', 'Gold 18K'), ('SILVER', 'Silver'), ('FIXED', 'Fixed Price (Manual)')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('GOLD_24K', 'Gold 24K'), ('GOLD_22K', 'Gold 22K'), ('GOLD_18K', 'Gold 18K'), ('SILVER', 'Silver')], max_length=20)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metal_rates', to='core.shop')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
