# Generated by Django 4.2.30 on 2026-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_jewelleryitem_metal_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalrate',
            name='source',
            field=models.CharField(default='MANUAL', max_length=50),
        ),
    ]
