# Generated by Django 4.2.30 on 2026-07-01 10:55

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    JewelleryItem = apps.get_model('inventory', 'JewelleryItem')
    for row in JewelleryItem.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_metalrate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelleryitem',
            name='barcode_svg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='barcode_type',
            field=models.CharField(choices=[('CODE128', 'Code 128'), ('EAN13', 'EAN 13'), ('QR', 'QR Code')], default='CODE128', max_length=20),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='jewelleryitem',
            index=models.Index(fields=['shop', 'design_code'], name='inventory_j_shop_id_e80865_idx'),
        ),
        migrations.AddIndex(
            model_name='jewelleryitem',
            index=models.Index(fields=['uuid'], name='inventory_j_uuid_abf9d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='jewelleryitem',
            constraint=models.UniqueConstraint(fields=('shop', 'design_code'), name='unique_shop_design_code'),
        ),
    ]

