# Generated by Django 4.2.30 on 2026-07-01 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_jewelleryitem_barcode_svg_jewelleryitem_barcode_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelleryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.category'),
        ),
    ]
