# Generated by Django 4.2.30 on 2026-08-18 18:46

import core.validators
from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_jewelleryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_jewellery_image_path, validators=[core.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='item_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='jewelleryitem',
            index=models.Index(fields=['shop', 'created_at'], name='inventory_j_shop_id_2a32e6_idx'),
        ),
        migrations.AddIndex(
            model_name='jewelleryitem',
            index=models.Index(fields=['metal_type', 'price'], name='inventory_j_metal_t_aff28d_idx'),
        ),
    ]
